export const GET_ALL_EMAILS = 'GET_ALL_EMAILS';
export const SET_LOG_IN = 'SET_LOG_IN';
export const NEW_ERROR = 'NEW_ERROR';
export const SET_ACTIVE_TABLE_PAGE = 'SET_ACTIVE_TABLE_PAGE';
export const SET_ROWS_AMOUNT_PER_PAGE = 'SET_ROWS_AMOUNT_PER_PAGE';
export const SET_TOTAL_EMAILS_COUNT = 'SET_TOTAL_EMAILS_COUNT';
